version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:1.25-alpine
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./.docker/nginx/sites/dev.default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/ssl:/etc/nginx/ssl
            - ./src:/var/www/
            - ./.logs/nginx:/var/log/nginx
        depends_on:
            - php
        networks:
            - app-network

    redis:
        container_name: redis
        image: redis:7-alpine
        restart: unless-stopped
        privileged: true
        volumes:
            - ./.docker/redis/redis.conf:/usr/local/redis/redis.conf
            - ./.database/redis:/data
            - ./.logs/redis:/var/log/redis
        ports:
            - '6379:6379'
        command:
            - redis-server
            - /usr/local/redis/redis.conf
        networks:
            - app-network

    php:
        container_name: php8.3
        build:
            context: .
            dockerfile: ./.docker/php/8.3/Dockerfile
        restart: unless-stopped
        ports:
            - '3000:3000'
            - '4000:4000'
            - '5173:5173'
            - '8000:8000'
            - '8080:8080'
        expose:
            - '9000'
        volumes:
            - ./src:/var/www/
            - ./.database/sqlite:/var/www/database
            - ./.logs/php:/var/log/php
        environment:
            PHP_IDE_CONFIG: 'serverName=Docker-php'
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/database/database.sqlite
            WORK_DIR: /var/www
            APP_ENV: dev
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
